language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python -m virtualenv .env
    find .env -name site-packages -exec bash -c 'echo "../../../../" > {}/self.pth' \;
  - pytest --cov-report term --cov=mindreader
after_success:
  - codecov